"""Initial migration for SQLite

Revision ID: e9dc54207ed6
Revises: 
Create Date: 2025-11-26 08:22:08.090798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9dc54207ed6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_tickers',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('active_subscriber_count', sa.Integer(), nullable=False),
    sa.Column('last_scan_at', sa.DateTime(), nullable=True),
    sa.Column('scan_tier', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    with op.batch_alter_table('master_tickers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_master_tickers_ticker'), ['ticker'], unique=False)

    op.create_table('option_chain_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('as_of_ts', sa.DateTime(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('underlying_price', sa.Float(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('option_chain_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_option_chain_snapshots_ticker'), ['ticker'], unique=False)

    op.create_table('signals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('as_of_ts', sa.DateTime(), nullable=False),
    sa.Column('front_expiry', sa.Date(), nullable=False),
    sa.Column('back_expiry', sa.Date(), nullable=False),
    sa.Column('front_dte', sa.Integer(), nullable=False),
    sa.Column('back_dte', sa.Integer(), nullable=False),
    sa.Column('front_iv', sa.Float(), nullable=False),
    sa.Column('back_iv', sa.Float(), nullable=False),
    sa.Column('sigma_fwd', sa.Float(), nullable=False),
    sa.Column('ff_value', sa.Float(), nullable=False),
    sa.Column('vol_point', sa.String(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('reason_codes', sa.JSON(), nullable=True),
    sa.Column('dedupe_key', sa.String(), nullable=False),
    sa.Column('underlying_price', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signals_as_of_ts'), ['as_of_ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_dedupe_key'), ['dedupe_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_signals_ff_value'), ['ff_value'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_ticker'), ['ticker'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('telegram_chat_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('telegram_username', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_telegram_chat_id'), ['telegram_chat_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_telegram_username'), ['telegram_username'], unique=False)

    op.create_table('signal_user_decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('signal_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('decision_ts', sa.DateTime(), nullable=False),
    sa.Column('decision_metadata', sa.JSON(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signal_user_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signal_user_decisions_signal_id'), ['signal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signal_user_decisions_user_id'), ['user_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'ticker'),
    sa.UniqueConstraint('user_id', 'ticker', name='uq_user_ticker')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_ticker'), ['ticker'], unique=False)

    op.create_table('user_settings',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('ff_threshold', sa.Float(), nullable=False),
    sa.Column('dte_pairs', sa.JSON(), nullable=True),
    sa.Column('vol_point', sa.String(), nullable=False),
    sa.Column('min_open_interest', sa.Integer(), nullable=False),
    sa.Column('min_volume', sa.Integer(), nullable=False),
    sa.Column('max_bid_ask_pct', sa.Float(), nullable=False),
    sa.Column('sigma_fwd_floor', sa.Float(), nullable=False),
    sa.Column('stability_scans', sa.Integer(), nullable=False),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('quiet_hours', sa.JSON(), nullable=True),
    sa.Column('preferred_structure', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('scan_priority', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_ticker'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('signal_user_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signal_user_decisions_user_id'))
        batch_op.drop_index(batch_op.f('ix_signal_user_decisions_signal_id'))

    op.drop_table('signal_user_decisions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_username'))
        batch_op.drop_index(batch_op.f('ix_users_telegram_chat_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_ticker'))
        batch_op.drop_index(batch_op.f('ix_signals_ff_value'))
        batch_op.drop_index(batch_op.f('ix_signals_dedupe_key'))
        batch_op.drop_index(batch_op.f('ix_signals_as_of_ts'))

    op.drop_table('signals')
    with op.batch_alter_table('option_chain_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_option_chain_snapshots_ticker'))

    op.drop_table('option_chain_snapshots')
    with op.batch_alter_table('master_tickers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_tickers_ticker'))

    op.drop_table('master_tickers')
    # ### end Alembic commands ###
