"""add entry_price and notes to decisions

Revision ID: 12db18512495
Revises: adaef6b48b3a
Create Date: 2025-11-26 07:55:01.733943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12db18512495'
down_revision = 'adaef6b48b3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signal_user_decisions', sa.Column('entry_price', sa.Float(), nullable=True))
    op.add_column('signal_user_decisions', sa.Column('notes', sa.String(), nullable=True))
    # op.create_unique_constraint('uq_user_ticker', 'subscriptions', ['user_id', 'ticker'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_ticker', 'subscriptions', type_='unique')
    op.drop_column('signal_user_decisions', 'notes')
    op.drop_column('signal_user_decisions', 'entry_price')
    # ### end Alembic commands ###
