"""add pnl columns to decisions

Revision ID: adaef6b48b3a
Revises: 004
Create Date: 2025-11-26 07:36:17.808913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adaef6b48b3a'
down_revision = '004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signal_user_decisions', sa.Column('pnl', sa.Float(), nullable=True))
    op.add_column('signal_user_decisions', sa.Column('exit_price', sa.Float(), nullable=True))
    op.drop_constraint('signals_dedupe_key_key', 'signals', type_='unique')
    op.drop_index('ix_signals_dedupe_key', table_name='signals')
    op.create_index(op.f('ix_signals_dedupe_key'), 'signals', ['dedupe_key'], unique=True)
    # op.create_unique_constraint('uq_user_ticker', 'subscriptions', ['user_id', 'ticker'])
    op.drop_constraint('users_telegram_chat_id_key', 'users', type_='unique')
    op.drop_index('ix_users_telegram_chat_id', table_name='users')
    op.create_index(op.f('ix_users_telegram_chat_id'), 'users', ['telegram_chat_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_chat_id'), table_name='users')
    op.create_index('ix_users_telegram_chat_id', 'users', ['telegram_chat_id'], unique=False)
    op.create_unique_constraint('users_telegram_chat_id_key', 'users', ['telegram_chat_id'])
    op.drop_constraint('uq_user_ticker', 'subscriptions', type_='unique')
    op.drop_index(op.f('ix_signals_dedupe_key'), table_name='signals')
    op.create_index('ix_signals_dedupe_key', 'signals', ['dedupe_key'], unique=False)
    op.create_unique_constraint('signals_dedupe_key_key', 'signals', ['dedupe_key'])
    op.drop_column('signal_user_decisions', 'exit_price')
    op.drop_column('signal_user_decisions', 'pnl')
    # ### end Alembic commands ###
